[project]
name = "apod_wallpaper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipython>=8.18.1",
    "nasapy>=0.2.7",
    "pandas>=2.3.3",
    "pillow>=11.3.0",
    "screeninfo>=0.8.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
"apod_wallpaper" = "src"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
